name: group_one_mobile_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

# dependencies:
#   flutter:
#     sdk: flutter
#   flutter_secure_storage: ^8.0.0
#   dio: ^5.4.0
#   path_provider: ^2.1.2
#   shared_preferences: ^2.2.2
#   universal_html: ^2.2.4
#   carousel_slider: ^4.2.1
#   shimmer: ^3.0.0
#   http: ^0.13.6
#   url_launcher: ^6.1.12
#   youtube_player_flutter: ^8.1.1
#   chewie: ^1.7.0
#   js: ^0.6.7

#   # The following adds the Cupertino Icons font to your application.
#   # Use with the CupertinoIcons class for iOS style icons.
#   cupertino_icons: ^1.0.8
#   provider: ^6.1.2 #for state management
#   flutter_dotenv: ^5.2.1
#   video_player: ^2.9.3
#   intl: ^0.20.2
#   flutter_svg: ^2.0.9

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0 # Keep only one version of intl, preferably the newer one ^0.20.2
  flutter_secure_storage: ^8.0.0
  dio: ^5.4.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  universal_html: ^2.2.4
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  http: ^0.13.6
  url_launcher: ^6.1.12
  youtube_player_flutter: ^8.1.1
  chewie: ^1.7.0
  js: ^0.6.7
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_dotenv: ^5.2.1
  video_player: ^2.9.3
  flutter_svg: ^2.0.9

  # dependencies:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/.env
    - assets/images/
    - assets/lang/
    - assets/lang/de.json
    - assets/lang/en.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
